services:
  backend:
    # image:node when you dont have a dockerfile
    build: ./backend #you already have a dockerfile in backend
    # environment:
    #   - PORT=7000
    
    #for all env var:
    env_file:
      - ./backend/.env
    ports:
      - 8000:7000
  
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    
  redis:
    image: redis #from docker hub
    ports:
      - 6379:6379